kind: pipeline
type: exec
name: frontend-build

platform:
  os: linux
  arch: amd64

steps:
- name: build backup source
  environment:
    buildShare: "/data/build_share"
    MAJOR_VERSION: "1.0.dev"
    DOCKER_HUB_USERNAME: "admin"
    DOCKER_HUB_PASSWORD: "HAR2019@har"    
  when:
    branch:
      - master
  commands:
    - sed -i "s/BUILD_VERSION='BLANK'/BUILD_VERSION='$MAJOR_VERSION.$DRONE_BUILD_NUMBER'/g" `pwd`/.env.local
    - cat `pwd`/.env.local
    - docker run --rm 
      -v $buildShare/yarn_cache:/usr/local/share/.cache/yarn 
      -v `pwd`:/src 
      --workdir /src
      node /bin/sh -c "node --version && yarn install && yarn run build"
    - cp `pwd`/default.template `pwd`/build
    - docker build 
     --tag klhar.ceshizhanyszweb.com/koala/koala_merchant_h5web:latest
     --tag klhar.ceshizhanyszweb.com/koala/koala_merchant_h5web:$MAJOR_VERSION.$DRONE_BUILD_NUMBER
     --file `pwd`/Dockerfile `pwd`/build
    - docker login klhar.ceshizhanyszweb.com --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
    - docker push klhar.ceshizhanyszweb.com/koala/koala_merchant_h5web:latest
    - docker push klhar.ceshizhanyszweb.com/koala/koala_merchant_h5web:$MAJOR_VERSION.$DRONE_BUILD_NUMBER
---
kind: pipeline
type: exec
name: deploy-to-dev60
node:
  runner_name: dev60  
steps:
- name: deploy to dev60
  environment:
    MAJOR_VERSION: "1.0.dev"
    DOCKER_HUB_USERNAME: "admin"
    DOCKER_HUB_PASSWORD: "HAR2019@har"        
  commands:
    - docker login klhar.ceshizhanyszweb.com --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
    - docker pull klhar.ceshizhanyszweb.com/panda/merchant_backweb:$MAJOR_VERSION.$DRONE_BUILD_NUMBER
    - docker rm panda_merchant_backweb -f || true 
    - docker run -d -it --name panda_merchant_backweb -p 26051:80 --link panda_merchant_api:api_host klhar.ceshizhanyszweb.com/panda/merchant_backweb:$MAJOR_VERSION.$DRONE_BUILD_NUMBER

depends_on:
- frontend-build    